archives:
  - files:
      # Ensure only built binary is archived
      - 'none*'
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    rlcp: true

before:
  hooks:
    - 'go mod download'
builds:
  # Check and build binary for 32-bit architecture (FreeBSD/ARM)
  - id: 32-bit-arch
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - '386'
    ldflags:
      - -s -w -X github.com/home-sol/multicast-proxy/cmd.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
snapshot:
  name_template: "{{ .Tag }}-next"