archives:
  - files:
      # Ensure only built binary is archived
      - 'none*'
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    rlcp: true

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
    ldflags:
      - '-s -w -X "github.com/home-sol/multicast-proxy/cmd.Version={{.Version}}"'
    mod_timestamp: '{{ .CommitTimestamp }}'
dockers:
- image_templates: ["ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/home-sol/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/home-sol/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates: ["ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/home-sol/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/home-sol/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
- name_template: ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/home-sol/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-arm64v8
checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
snapshot:
  name_template: "{{ .Tag }}-next"