archives:
  - files:
      # Ensure only built binary is archived
      - 'none*'
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    rlcp: true

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X cmd.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/home-sol/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/home-sol/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    image_templates:
      - "ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-armv6"
      - "ghcr.io/home-sol/{{ .ProjectName }}:latest-armv6"
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - "ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/home-sol/{{ .ProjectName }}:latest-armv7"
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: 0hlov3s/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/home-sol/{{ .ProjectName }}:{{ .Version }}-armv7
  - name_template: 0hlov3s/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/home-sol/{{ .ProjectName }}:latest-amd64
      - ghcr.io/home-sol/{{ .ProjectName }}:latest-arm64v8
      - ghcr.io/home-sol/{{ .ProjectName }}:latest-armv6
      - ghcr.io/home-sol/{{ .ProjectName }}:latest-armv7
checksum:
  algorithm: sha256
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
snapshot:
  name_template: "{{ .Tag }}-next"