name: 'Build CLI and attach to GitHub release'

on:
  release:
    types: [ published ]

  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: 'Build CLI and attach to GitHub release'
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: install libcap
        run: sudo apt-get install -y libpcap-dev

      # Checkout the repo
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Go
      - name: 'Setup Go'
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Print Go version
      - run: go version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and release
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --parallelism 2 --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
