name: 'Build CLI and attach to GitHub release'

on:
  release:
    types: [ published ]

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  statuses: write

jobs:
  build:
    name: 'Build CLI and attach to GitHub release'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Go
      - name: 'Setup Go'
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      # Print Go version
      - run: go version

      # Build and release
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --parallelism 2 --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
